### ISSUE TITLE
Remove "--talk-name=org.gtk.vfs.*"

### ISSUE THREAD

**Issue by hadess** [flathub/org.gnome.DejaDup#12]
This application probably doesn't need to talk to gvfs.

It has:
```
    "--talk-name=org.gtk.vfs.*"
```
in its manifest, but lacks "--talk-name=org.gtk.vfs" for this actually do anything useful. If you want to talk to gvfs to list mounts and drives, you probably want to add `"--talk-name=org.gtk.vfs"`

**Comment by hadess** [comment]
(Oh, and add access to `xdg-run/gvfsd` as per https://github.com/flathub/flathub/issues/2180)

**Comment by mikix** [comment]
> This application probably doesn't need to talk to gvfs.

It does - we use gvfs to support remote backup servers, via ssh, ftp, webdav, etc.

> If you want to talk to gvfs to list mounts and drives, you probably want to add "--talk-name=org.gtk.vfs"

I just tested and we seem to be able to list them just fine as-is. Looking at the running services in my session, I don't see a `org.gtk.vfs` name. The main daemon is at `org.gtk.vfs.Daemon` on my machine with gvfs 1.46 - which service claims `org.gtk.vfs`?

> (Oh, and add access to xdg-run/gvfsd as per flathub/flathub#2180)

This was [already done](https://github.com/flathub/org.gnome.DejaDup/commit/6c28c9d2b4d897ce63e977bd802795e1d75cdc1a).

I will optimistically close, but please let me know if I'm missing something around `org.gtk.vfs`.

**Comment by hadess** [comment]
> I just tested and we seem to be able to list them just fine as-is. Looking at the running services in my session, I don't see a `org.gtk.vfs` name. The main daemon is at `org.gtk.vfs.Daemon` on my machine with gvfs 1.46 - which service claims `org.gtk.vfs`?

You're completely right about `org.gtk.vfs`. I think that it was wrongly cargo-culted from the very first Flatpaks ever made, and never questioned.

@alexlarsson do you know why we added `org.gtk.vfs` as a D-Bus name to talk to for all those GNOME apps? Looks like `org.gtk.vfs.*` is the only one that needs to be there.

**Comment by alexlarsson** [comment]
I vaguely remember some renaming of the gvfs dbus names at some point, but really I don't remember. 
For anything remotely modern i thing org.gtk.vfs.* is fine.

**Comment by alexlarsson** [comment]
This was what i remembered: https://github.com/GNOME/gvfs/commit/59325dfbe1f855434f87b7791d11175bfdfb9766 which seems unrelated to org.gtk.vfs, so that can just be dropped.
