### ISSUE TITLE
Unable to lauch from KDE

### ISSUE THREAD

**Issue by ctron** [flathub/org.gnome.DejaDup#18]
Installing it via flatpak and then starting it from KDE results in an error popup with the message: "Launching Backups (Failed)" / "The name is not activatable".

Still one can start it from the command line using:

```shell
flatpak run org.gnome.DejaDup
```

**Comment by mikix** [comment]
Is this still a problem? I believe I've gotten other issue reports from KDE users for other things, but that clearly were from inside the actual program - which makes me think some other KDE folks can at least actually launch it.

**Comment by mikix** [comment]
(Which distro?)
