### ISSUE TITLE
Verify Déjà Dup Backups on Flathub

### ISSUE THREAD

**Issue by overwatcheddude** [flathub/org.gnome.DejaDup#32]
You can find the steps here:
https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by mikix** [comment]
We used to be verified, but then flathub changed how it handles org.gnome.* app ids.

This is currently blocked on https://gitlab.gnome.org/Infrastructure/Infrastructure/-/issues/1400

**Comment by mikix** [comment]
This is now done!
