### ISSUE TITLE
No longer starts on my pc

### ISSUE THREAD

**Issue by komorebithrowsatable** [flathub/org.gnome.DejaDup#5]
No longer able to start deja dup on my pc:

```
komorebi@komorebi-pc:~$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=deja-dup org.gnome.DejaDup

(org.gnome.DejaDup:2): GLib-GObject-WARNING **: 21:22:00.465: invalid (NULL) pointer instance

(org.gnome.DejaDup:2): GLib-GObject-CRITICAL **: 21:22:00.465: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(deja-dup-monitor:7): GLib-GObject-WARNING **: 21:22:00.489: invalid (NULL) pointer instance

(deja-dup-monitor:7): GLib-GObject-CRITICAL **: 21:22:00.489: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

```
After start it consumes ~10mb of ram. Application window never appears. Os/hardware information:

Operating System: KDE neon 5.19
KDE Plasma Version: 5.19.4
KDE Frameworks Version: 5.73.0
Qt Version: 5.14.2
Kernel Version: 5.4.0-42-generic
OS Type: 64-bit
Processors: 4 × Intel® Xeon® CPU E3-1225 V2 @ 3.20GHz
Memory: 23,4 GiB of RAM
Graphics Processor: Radeon RX550/550 Series

It was working fine 2 weeks ago, so probably the problem is caused by the last update. Can you please fix? Thanks.

**Comment by mikix** [comment]
Hello and thank you for the report!

Hrm. I'm running the flatpak locally and it works OK here. I'm running in GNOME though... I'll try in KDE, but not sure why that would cause something like this.

**Comment by komorebithrowsatable** [comment]
Sorry, my bad. It seems like the issue is caused by flatpak service itself.
